/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Simplecomputer.glb -o src/components/Camping.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Camping(props) {
  const { nodes, materials } = useGLTF('/models/Simplecomputer.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="group1631870305" geometry={nodes.group1631870305.geometry} material={materials.mat21} />
        <mesh name="group2131501692" geometry={nodes.group2131501692.geometry} material={materials.mat17} />
        <mesh name="group2115554823" geometry={nodes.group2115554823.geometry} material={materials.mat15} />
        <mesh name="group861517382" geometry={nodes.group861517382.geometry} material={materials.mat15} />
        <mesh name="group1262710399" geometry={nodes.group1262710399.geometry} material={materials.mat17} />
        <mesh name="group721205586" geometry={nodes.group721205586.geometry} material={materials.mat22} />
        <mesh name="group35764393" geometry={nodes.group35764393.geometry} material={materials.mat22} />
        <mesh name="group524729728" geometry={nodes.group524729728.geometry} material={materials.mat9} />
        <mesh name="group1639888595" geometry={nodes.group1639888595.geometry} material={materials.mat21} />
        <mesh name="group1982090435" geometry={nodes.group1982090435.geometry} material={materials.mat22} />
        <mesh name="group1164002630" geometry={nodes.group1164002630.geometry} material={materials.mat22} />
        <mesh name="group1127867106" geometry={nodes.group1127867106.geometry} material={materials.mat22} />
        <mesh name="group944565295" geometry={nodes.group944565295.geometry} material={materials.mat22} />
        <mesh name="group1420559667" geometry={nodes.group1420559667.geometry} material={materials.mat22} />
        <mesh name="group646619783" geometry={nodes.group646619783.geometry} material={materials.mat22} />
        <mesh name="group2085192078" geometry={nodes.group2085192078.geometry} material={materials.mat22} />
        <mesh name="group1506597832" geometry={nodes.group1506597832.geometry} material={materials.mat22} />
        <mesh name="group1412601270" geometry={nodes.group1412601270.geometry} material={materials.mat22} />
        <mesh name="group2130073709" geometry={nodes.group2130073709.geometry} material={materials.mat22} />
        <mesh name="group1215636041" geometry={nodes.group1215636041.geometry} material={materials.mat22} />
        <mesh name="group354029567" geometry={nodes.group354029567.geometry} material={materials.mat22} />
        <mesh name="group541733156" geometry={nodes.group541733156.geometry} material={materials.mat22} />
        <mesh name="group188804331" geometry={nodes.group188804331.geometry} material={materials.mat22} />
        <mesh name="group24878451" geometry={nodes.group24878451.geometry} material={materials.mat22} />
        <mesh name="group618472546" geometry={nodes.group618472546.geometry} material={materials.mat22} />
        <mesh name="group2031044348" geometry={nodes.group2031044348.geometry} material={materials.mat22} />
        <mesh name="group1344882062" geometry={nodes.group1344882062.geometry} material={materials.mat22} />
        <mesh name="group51422144" geometry={nodes.group51422144.geometry} material={materials.mat22} />
        <mesh name="group627458418" geometry={nodes.group627458418.geometry} material={materials.mat22} />
        <mesh name="group1312281953" geometry={nodes.group1312281953.geometry} material={materials.mat22} />
        <mesh name="group1139380957" geometry={nodes.group1139380957.geometry} material={materials.mat22} />
        <mesh name="group806411317" geometry={nodes.group806411317.geometry} material={materials.mat22} />
        <mesh name="group396267525" geometry={nodes.group396267525.geometry} material={materials.mat22} />
        <mesh name="group1625508101" geometry={nodes.group1625508101.geometry} material={materials.mat22} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Simplecomputer.glb')
